# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

doublesum <- function(xy, mark, r) {
    .Call('_bivpower_doublesum', PACKAGE = 'bivpower', xy, mark, r)
}

doublesum22 <- function(xy, r) {
    .Call('_bivpower_doublesum22', PACKAGE = 'bivpower', xy, r)
}

g_doublesum <- function(xy, mark, r, bw, kern = 1L) {
    .Call('_bivpower_g_doublesum', PACKAGE = 'bivpower', xy, mark, r, bw, kern)
}

g_doublesum_asym <- function(xy, mark, r, bw12, bw21, kern = 1L) {
    .Call('_bivpower_g_doublesum_asym', PACKAGE = 'bivpower', xy, mark, r, bw12, bw21, kern)
}

evaluate_lambda_c <- function(snfield, x) {
    .Call('_bivpower_evaluate_lambda_c', PACKAGE = 'bivpower', snfield, x)
}

rcox_MH <- function(n, win, snfield, iter, dbg) {
    .Call('_bivpower_rcox_MH', PACKAGE = 'bivpower', n, win, snfield, iter, dbg)
}

rcox_thin <- function(win, snfield, dbg) {
    .Call('_bivpower_rcox_thin', PACKAGE = 'bivpower', win, snfield, dbg)
}

mc_triple_integral_ball <- function(bbox, r, n) {
    .Call('_bivpower_mc_triple_integral_ball', PACKAGE = 'bivpower', bbox, r, n)
}

mc_triple_integral_ball_matrix <- function(bbox, r, n) {
    .Call('_bivpower_mc_triple_integral_ball_matrix', PACKAGE = 'bivpower', bbox, r, n)
}

mc_triple_integral_annuli <- function(bbox, r, h, n) {
    .Call('_bivpower_mc_triple_integral_annuli', PACKAGE = 'bivpower', bbox, r, h, n)
}

mc_triple_integral_annuli_matrix <- function(bbox, r, h, n) {
    .Call('_bivpower_mc_triple_integral_annuli_matrix', PACKAGE = 'bivpower', bbox, r, h, n)
}

